package jeu;

public enum EntityType {
	PLAYER_RED, PLAYER_YELLOW, PLAYER_BLUE, PLAYER_GREEN, PLAYER_DARK,
	PLAYERCOMPONENT, LINEOFUI, INFOUI, RANGE, SPELL, GRID, BLOCK, GOBLIN, DESCRIPTION, FACE,
	PARTICLE, ANIMATED_BORDER, RANGE_SPELL
}
